version: "3"
services:
  mysql-master:
    image: mysql-master
    container_name: mysql-master
    build: 
      context: ./
      dockerfile: master/Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: 'jutopia'
      MYSQL_USER: 'juto'
      MYSQL_PASSWORD: 'juto1234'
      MYSQL_ROOT_PASSWORD: 'juto1234'
    ports:
      - '3306:3306'
    # Where our data will be persisted
    volumes:
      - ~/data/mysql/master:/var/lib/mysql
      - ~/data/mysql/master:/var/lib/mysql-files
    networks:
      - jutopia-network
  
  mysql-slave:
    image: mysql-slave
    container_name: mysql-slave
    build: 
      context: ./
      dockerfile: slave/Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: 'jutopia'
      MYSQL_USER: 'juto'
      MYSQL_PASSWORD: 'juto1234'
      MYSQL_ROOT_PASSWORD: 'juto1234'
    ports:
      - '3307:3306'
    # Where our data will be persisted
    volumes:
      - ~/data/mysql/slave:/var/lib/mysql
      - ~/data/mysql/slave:/var/lib/mysql-files
    networks:
      - jutopia-network
  
# Names our volume
volumes:
  my-db-master:
  my-db-slave: 

networks: 
  jutopia-network:
    external: true
    # name: jutopia-network
    # driver: bridge