server:
  port: 0

spring:
  application:
    name: rent-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  # 빌드시 config 서버에서 불러오지 못하는 문제 발생 -> 직접 추가
  data:
    redis:
      url: redis://j9c108.p.ssafy.io:46379/

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

springdoc:
  api-docs:
    path: /rent-server/v3/api-docs
  swagger-ui:
    path: /rent-server/swagger-ui.html

openapi:
  service:
    # API Gateway 포트
    url: http://localhost:8000

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh


