server:
  port: 0

spring:
  application:
    name: bank-service
  profiles:
    active: local     # 애플리케이션 환경 = local, dev
  config:
    import: optional:bankserver:http://localhost:8888 # import:optional:configserver사용 -> Spring cloud config server 주소


