server:
  port: 8761
spring:
  application:
    name: discovery-server
  cloud:
    config:
      uri: http://127.0.0.1:8888
      name: jutopia
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
